#!/usr/bin/perl -w

# Highlights tabs and trailing whitespace in source code and text files.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is free
# and unencumbered software released into the public domain. For more
# information, please refer to the accompanying "UNLICENCE" file.

use strict;

use File::Basename;
use Getopt::Long;

# TODO: Add help documentation.
our ($opt_suppress_tabs, $opt_suppress_whitespace);
GetOptions("suppress-tabs|t", "suppress-whitespace|w");
while (<>) {
  print {*STDERR} "$ARGV:$.:$-[0]: One or more tabs.\n"
      if (/\t/ and not defined($opt_suppress_tabs));
  print {*STDERR} "$ARGV:$.:$-[0]: Trailing whitespace.\n" if
      (/[ \t]+$/ and not defined($opt_suppress_whitespace));
  close ARGV if eof;
}
