#!/bin/sh
# Clean up images of inked line-art by removing any blue under-drawings,
# fiddling with black and white levels, and applying some other tricks.
# Requires ImageMagick.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is free
# and unencumbered software released into the public domain. For more
# information, please refer to the accompanying "UNLICENCE" file.

BLACK_POINT="60%"
WHITE_POINT="45%"
USAGE=$(cat <<USAGE;
"$(basename $0)" cleans up images of inked line-art.
Usage: $(basename $0) [options] [input-filename] [output-filename]
Options:
  -b PERCENTAGE    Set the black point (default is $BLACK_POINT). 
  -w PERCENTAGE    Set the white point (default is $WHITE_POINT).
USAGE)
while getopts ":b:hw:" OPTIONS; do
  case $OPTIONS in
    # TODO: Handle non-percentage values.
    b) BLACK_POINT=$OPTARG;;
    h) echo "$USAGE"; exit;;
    w) WHITE_POINT=$OPTARG;;
    \?) echo "Unknown option: $OPTARG\n$USAGE" >&2; exit 2;;
    :) echo "Option $OPTARG requires an argument\n$USAGE" >&2; exit 2;;
  esac
done
shift $((OPTIND-1))
[[ "$#" -lt 2 ]] && { echo "Not enough operands\n$USAGE" >&2; exit 2; }
convert $1 -channel B -modulate 100,0,100 +channel \
    -level $WHITE_POINT,$BLACK_POINT +level-colors black,white $2
# TODO: Make the background transparent.
