#!/usr/bin/env python3
"""
A simple dotfile-installing script.

This file was written by Damien Dart, <damiendart@pobox.com>. This is
free and unencumbered software released into the public domain. For
more information, please refer to the accompanying "UNLICENCE" file.
"""

import os
import pathlib
import sys

files = [
  '.bash_profile',
  '.bashrc',
  '.gitconfig',
  '.gitignore',
  '.profile',
  '.shellrc',
  '.vimrc',
  '.zprofile',
  '.zshrc',
]

for file in files:
  destination = pathlib.Path(pathlib.Path.home(), file)
  source = pathlib.Path(sys.path[0], file).resolve()

  if (os.path.exists(destination)):
    if (os.path.samefile(destination.resolve(), source)):
      print('[✔] Link to "' + str(source) + '" already exists')
    else:
      print('[✘] "' + str(destination) + '" already exists')
  else:
    os.symlink(source, destination)
    print('[✔] Created link to "' + str(source) + '"')
