#!/usr/bin/env python3
"""
A simple dotfile-installing script.

This file was written by Damien Dart, <damiendart@pobox.com>. This is
free and unencumbered software released into the public domain. For
more information, please refer to the accompanying "UNLICENCE" file.
"""

import os
import pathlib
import sys

errors = False
files = [
    '.bash_profile',
    '.bashrc',
    '.config/ranger/rc.conf',
    '.gitconfig',
    '.gitignore',
    '.ideavimrc',
    '.profile',
    '.shellrc',
    '.tmux.conf',
    '.vimrc',
]

if __name__ == '__main__':
    for file in files:
        destination = pathlib.Path(pathlib.Path.home(), file)
        source = pathlib.Path(sys.path[0], file).resolve()

        if os.path.exists(destination):
            if os.path.samefile(destination.resolve(), source):
                print('[✔] Link to "' + str(source) + '" already exists')
            else:
                print('[✘] "' + str(destination) + '" already exists')
                errors = True
        else:
            if os.path.islink(destination):
                print('[✘] "' + str(destination) + '" is a dangling symlink')
                errors = True
            else:
                if "/" in file:
                    os.makedirs(os.path.dirname(destination), 0o700, True)

                os.symlink(source, destination)
                print('[✔] Created link to "' + str(source) + '"')

    print('\nIf any shell-related dotfiles have changed, you may need to log out and')  # noqa:501
    print('log back in, or "source" any new dotfiles so that they take effect in')  # noqa:501
    print('the current interactive shell session.')

    if errors:
        sys.exit(1)
