#!/usr/bin/perl -w

# Checks MP3 files for some missing tags and minor tag nit-picks.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is free
# and unencumbered software released into the public domain. For more
# information, please refer to the accompanying "UNLICENCE" file.

use strict;

use MP3::Tag;

foreach (@ARGV) {
  my $mp3_file = MP3::Tag->new($_) or die("Unable to read \"$_\", stopped");
  my @missing_tag_checks = (["album artist", "TPE2"], ["album title", "TALB"],
      ["artist", "TPE1"], ["disc number", "TPOS"], ["genre", "TCON"],
      ["title", "TIT2"], ["track number", "TRCK"], ["year", "TYER"]);
  for my $i (0 .. $#missing_tag_checks) {
    print {*STDERR} "$_: ${\ucfirst($missing_tag_checks[$i][0])} tag missing.\n"
        if not defined $mp3_file->select_id3v2_frame_by_descr($missing_tag_checks[$i][1]);
    if ($missing_tag_checks[$i][1] eq "TIT2") {
      print {*STDERR} "$_: ${\ucfirst($missing_tag_checks[$i][0])} has junk.\n"
          if defined $mp3_file->select_id3v2_frame_by_descr("TIT2") and
          $mp3_file->select_id3v2_frame_by_descr("TIT2") =~ /(explicit|album version)/i;
    }
  }
}
