#!/usr/bin/env python

"""A dynamic-DNS thing for NearlyFreeSpeech.NET-managed domains.

This file was written by Damien Dart, <damiendart@pobox.com>. This is
free and unencumbered software released into the public domain. For more
information, please refer to the accompanying "UNLICENCE" file.
"""


import ConfigParser
import json
import nfsnapi
import os
import sys
import urllib2


if __name__ == "__main__":
  try:
    config = ConfigParser.ConfigParser()
    config.read(["nfsnddns.cfg", os.path.expanduser("~/.nfsnddns.cfg"),
        os.path.expanduser("~/nfsnddns.cfg")])
    API_key = config.get("credentials", "apikey")
    domain_name = config.get("domain", "domainname")
    sub_domain = config.get("domain", "subdomain")
    username = config.get("credentials", "username")
    # TODO: Check if IP addresses are being returned.
    old_ip_address = json.loads(nfsnapi.run_request(username, API_key,
        "/dns/%s/listRRs" % domain_name, "name=%s" % sub_domain))[0]["data"]
    new_ip_address = urllib2.urlopen("http://icanhazip.com").read().rstrip()
    if (old_ip_address != new_ip_address):
      nfsnapi.run_request(username, API_key, "/dns/%s/removeRR" % domain_name,
          "name=%s&type=A&data=%s" % (sub_domain, old_ip_address))
      nfsnapi.run_request(username, API_key, "/dns/%s/addRR" % domain_name,
          "name=%s&type=A&data=%s&ttl=180" % (sub_domain, new_ip_address))
      print "<http://%s.%s/> now points to %s." % (sub_domain, domain_name,
          new_ip_address)
  except ConfigParser.Error as e:
    print "ERROR: Unable to parse configuration file.\n" + str(e)
    # TODO: Add usage instructions.
    sys.exit(1)
  except nfsnapi.NFSNAPIRequestError as e:
    print "ERROR: " + str(e)
