#!/bin/sh
#
# A simple Pinboard backup script.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE

USAGE=`cat <<USAGE;
USAGE: $(basename $0) BACKUP-XML-DESTINATION AUTH-TOKEN`
[ "$#" -lt 2 ] && { printf "Not enough operands\n$USAGE\n" >&2; exit 2; }
if [ ! -f ~/.pinboardbackup ] || [ `find ~/.pinboardbackup -mmin +5;` ]; then
  # TODO: Handle "429 Too Many Requests" server errors?
  # TODO: Prettify XML output?
  curl -s "https://api.pinboard.in/v1/posts/all?auth_token=$2" -o $1
  date +"Last backup: %c" > ~/.pinboardbackup
else
  echo "ERROR: You're hitting the Pinboard API too often!" >&2
  echo "See <https://pinboard.in/api/#limits> for more information." >&2
  exit 2
fi
