# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE file.
---

version: '3'

output: 'prefixed'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'dependencies'
      - task: 'lint'
    desc: 'Run all CI-related tasks'

  dependencies:
    cmds:
      - cmd: 'shellcheck -V 1&>/dev/null || (echo "ERROR: Shellcheck is not installed!"; exit 1)'
      - task: 'dependencies:git-submodules'
      - task: 'dependencies:python'
    desc: 'Run all dependency-installing tasks'

  dependencies:git-submodules:
    cmds:
      - 'git submodule sync'
      - 'git submodule update'
    desc: 'Initial and update Git submodules'

  dependencies:python:
    cmds:
      - 'pip3 install -r requirements.txt'
    desc: 'Install Python dependencies'

  lint:
    cmds:
      - task: 'lint:python'
      - task: 'lint:shell'
    desc: 'Run all linting-related tasks'

  lint:python:
    cmds:
      - task: 'lint:python:black'
      - task: 'lint:python:flake8'
    desc: 'Run all Python linting tasks'

  lint:python:black:
    cmds:
      - 'black --check install bin/markdown-tidy'
    desc: 'Lint Python scripts with Black'

  lint:python:flake8:
    cmds:
      - 'flake8 install bin/markdown-tidy'
    desc: 'Lint Python scripts with Flake8'

  lint:shell:
    cmds:
      - >-
        shellcheck
        .bash_profile
        .bashrc
        .profile
        .shellrc
        bin/fuzzy-*
        bin/pinboardbackup
    desc: 'Lint shell configuration files and scripts with ShellCheck'
