# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE file.
---

version: 2

output: 'prefixed'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'dependencies'
      - task: 'lint'
    desc: 'Run all CI-related tasks'

  dependencies:
    cmds:
      # ShellCheck is required for linting shell-related files and
      # currently must be installed manually.
      - 'pip3 install -r requirements.txt'
    desc: 'Install Python dependencies'

  lint:
    cmds:
      - task: 'lint:python'
      - task: 'lint:shell'
    desc: 'Run all linting-related tasks'

  lint:python:
    cmds:
      - 'flake8 install'
    desc: 'Lint Python scripts with Flake8'

  lint:shell:
    cmds:
      - 'shellcheck .bash_profile .bashrc .profile .shellrc .zprofile .zshrc bin/pinboardbackup'
    desc: 'Lint shell configuration files and scripts with ShellCheck'
