# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE file.
---

version: 2

output: 'prefixed'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'lint'
    desc: 'Run all CI-related tasks'

  lint:
    cmds:
      - task: 'lint:shell'
    desc: 'Run all linting-related tasks'

  lint:shell:
    cmds:
      - 'shellcheck .bash_profile .bashrc .profile .shellrc .zprofile .zshrc bin/pinboardbackup'
    desc: 'Lint shell configuration files and scripts with ShellCheck'
