# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
name: 'Lint Project'

on:
  push:
    branches:
      - 'master'

jobs:
  lint-yaml:
    name: 'Lint project'
    runs-on: 'ubuntu-18.04'
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v1'

      # The version of ShellCheck installed via APT is a little
      # out-of-date and doesn't support the "shell" directive required
      # for checking ".zshrc" and ".zprofile".
      - name: 'Install ShellCheck'
        run: |
          wget -qO- https://github.com/koalaman/shellcheck/releases/download/v0.7.0/shellcheck-v0.7.1.linux.x86_64.tar.xz | tar -xJf -
          sudo cp shellcheck-v0.7.1/shellcheck /usr/local/bin

      - name: 'Install Task'
        run: 'curl -sL https://taskfile.dev/install.sh | sh'

      - name: 'Run all linting-related tasks'
        run: './bin/task ci'
